### ISSUE TITLE
Question: static variable allocated with umpire

### ISSUE THREAD

**Issue by mclarsen** [LLNL/Umpire#353]
Background: I have an array class that uses umpire to allocate and deallocate memory. I have a need to store some resources statically (for performance reasons), but if I have an Array  class that is statically declared I have a problem. When it comes time to destruct it, I ask umpire for the "host" allocator, which i assume is stored inside a static variable, but the issue is that the variable that stores the allocator is already gone, i.e. when I ask for the allocators it does not exist and an exception is thrown.

Is there a way around this? I have a workaround for now, but its not ideal.

**Comment by davidbeckingsale** [comment]
Hey @mclarsen - how would you want this to work? It's really hard to deal with stuff at shutdown like this since you cannot order the destruction of objects correctly. You might be able to "hold on" to the resource manager in your static object such that the order ends up being correct.

All allocators will exist until the ResourceManager is destroyed.

**Comment by mclarsen** [comment]
This isn't anything critical. I agree that his is hard and dangerous (order of statically destructed objects). I just wanted to see if you had any thoughts. If I ever end up with a critical case, then I might revisit.
