### ISSUE TITLE
Custom alignment doesn't work in DynamicPoolMap

### ISSUE THREAD

**Issue by tepperly** [LLNL/Umpire#358]
**Describe the bug**

```C++
#include <cstdlib>
#include <iostream>
#include <umpire/Umpire.hpp>

int
main(int argc, char **argv)
{
  int numIter=16;
  if (2 == argc) {
    numIter = std::atoi(argv[1]);
  }
  auto &rm(umpire::ResourceManager::getInstance());
  auto host(rm.getAllocator("HOST"));
  auto pool(rm.makeAllocator<umpire::strategy::DynamicPool>("HOST_pool",
                                                            host,
                                                            512*1024*1024,
                                                            1024*1024, 64));
  for(int i =0 ; i < numIter; ++i) {
    void *ptr(pool.allocate(2048));
    if (0 != (reinterpret_cast<std::ptrdiff_t>(ptr) % 64)) {
      std::cerr << "Pointer is not 64-byte aligned: " << ptr << "\n";
    }
  }
}
```

**To Reproduce**

Compile the program above and run.  Pointer return isn't 64-byte aligned as requested.

**Expected behavior**

I expected allocate to return 64-byte aligned memory addresses.

**Compilers & Libraries (please complete the following information):**

g++ version 8.3.1 20190223 (Red Hat 8.3.1-2)

**Additional context**

**Comment by davidbeckingsale** [comment]
Hey @tepperly  - this is fixed by #359 . The pools assume you will want alignment based on the underlying allocator. For CPU memory, the AlignedAllocator will let you chose any power of 2 alignment >= 16. You can then either create a pool on top of that AlignedAllocator with your desired alignment, or ignore the aligment of the pool, and create the AlignedAllocator on top of the pool. The first approach will be more space efficient.
