### ISSUE TITLE
Link hypre with umpire using host linker

### ISSUE THREAD

**Issue by liruipeng** [LLNL/Umpire#652]
Hi, Umpire developers,

We now use host linker for the drivers in hypre. With Umpire, we got the following error,
```
Building ij ... 
mpixlC -o ij ij.o -L/g/g92/li50/workspace/hypre/test/src/hypre/lib -lHYPRE -Wl,-rpath,/g/g92/li50/workspace/hypre/test/src/hypre/lib           -lm  -L/usr/tce/packages/cuda/cuda-10.1.243/lib64 -lcudart -lcusparse -lcurand      -L/usr/workspace/li50/Umpire-git/Umpire/install_xlC_lassen/lib  -lumpire 
/usr/workspace/li50/Umpire-git/Umpire/install_xlC_lassen/lib/libumpire.a(Allocator.cpp.o): In function `__sti____cudaRegisterAll()':
/var/tmp/li50/tmpxft_000189aa_00000000-5_Allocator.cudafe1.cpp:(.text+0xac0): undefined reference to `__cudaRegisterLinkedBinary_44_tmpxft_000189aa_00000000_6_Allocator_cpp1_ii_a17095a1'
/usr/workspace/li50/Umpire-git/Umpire/install_xlC_lassen/lib/libumpire.a(Replay.cpp.o): In function `__sti____cudaRegisterAll()':
/var/tmp/li50/tmpxft_000189ab_00000000-5_Replay.cudafe1.cpp:(.text+0x5d4): undefined reference to `__cudaRegisterLinkedBinary_41_tmpxft_000189ab_00000000_6_Replay_cpp1_ii_5eca6429'
/usr/workspace/li50/Umpire-git/Umpire/install_xlC_lassen/lib/libumpire.a(ResourceManager.cpp.o): In function `__sti____cudaRegisterAll()':
/var/tmp/li50/tmpxft_000189ac_00000000-5_ResourceManager.cudafe1.cpp:(.text+0x22134): undefined reference to `__cudaRegisterLinkedBinary_50_tmpxft_000189ac_00000000_6_ResourceManager_cpp1_ii_42a9a1b2'
/usr/workspace/li50/Umpire-git/Umpire/install_xlC_lassen/lib/libumpire.a(Umpire.cpp.o): In function `__sti____cudaRegisterAll()':
/var/tmp/li50/tmpxft_000189ad_00000000-5_Umpire.cudafe1.cpp:(.text+0x3088): undefined reference to `__cudaRegisterLinkedBinary_41_tmpxft_000189ad_00000000_6_Umpire_cpp1_ii_4507af2f'
make: *** [Makefile:138: ij] Error 1
```
It seems that we need a separable compilation step for `libumpire.a`. I did this by
```
/usr/tce/packages/cuda/cuda-10.1.243/bin/nvcc -ccbin=mpixlC -gencode arch=compute_70,code=sm_70 -dlink /usr/workspace/li50/Umpire-git/Umpire/install_xlC_lassen/lib/libumpire.a -o dlink.o
```
and added `dlink.o` to the link line, and it worked.

Are we supposed to do this on our side?

Thanks

-Ruipeng

**Comment by davidbeckingsale** [comment]
Yes, unfortunately for now that is required since we provide a DeviceAllocator which exposes device code. In future, we are looking at ways to avoid this by potentially providing a separate `libumpire_device.a` which would contain all the the device symbols and could be omitted if you aren't using them.

**Comment by msimberg** [comment]
Sorry for bumping an old issue but since this is still an issue I thought I'd start here. Happy to open a separate issue if that's better.

Basically I'm wondering if there are any updated plans on providing the separate library with device symbols? Are there any (known) technical or other reasons not to do that yet? If not I may even be interested in putting together a PR to separate those symbols out.

**Comment by davidbeckingsale** [comment]
Hey @msimberg - no plans as of yet, but we would be happy to help you with a PR if this is an immediate need for you.

**Comment by msimberg** [comment]
Great, thanks @davidbeckingsale! It's only a small annoyance but I'm hoping the fix is also relatively small... let's see. I'll have a go at this.
